Feat/theme improvements
Prime-Holding/widget_toolkit pull request #101
Opened 2024-04-01 20:31 UTC by DDavidPrime

Closes #82

2024-04-02 08:39 UTC, StanevPrime requested changes

2024-04-02 08:39 UTC, StanevPrime commented on packages/widget_toolkit/lib/src/base/theme/widget_toolkit_theme.dart
> +    required this.lightRed,
Please rename this property to its domain ... it will be confusing the set a `blue` color to a property, which is called `lightRed`

2024-04-02 08:39 UTC, StanevPrime commented on packages/widget_toolkit/lib/src/base/theme/widget_toolkit_theme.dart
> +    required this.lightRed,
This applies for all non-domain specifics properties

2024-04-02 08:39 UTC, StanevPrime commented on packages/widget_toolkit/lib/src/lib_edit_address/theme/edit_address_theme.dart
> +    required this.white,
Same as above

2024-04-02 08:39 UTC, StanevPrime commented on packages/widget_toolkit_otp/lib/src/base/theme/sms_code_theme.dart
> +    required this.gray,
Same as above

2024-04-02 08:39 UTC, StanevPrime commented on packages/widget_toolkit_pin/lib/src/base/utils/theme/pin_code_theme.dart
> +    required this.lightRed,
Same as above

2024-04-02 08:39 UTC, StanevPrime commented on packages/widget_toolkit_qr/lib/src/base/theme/qr_scanner_theme.dart
> +    required this.cameraPermission6,
`cameraPermission6` ? what does this mean. Please use more domain specific names

2024-04-02 08:39 UTC, StanevPrime commented on packages/widget_toolkit_qr/lib/src/base/theme/qr_scanner_theme.dart
> +    required this.qrScannerBlue,
Same as above

2024-04-04 10:18 UTC, StanevPrime requested changes

2024-04-04 10:18 UTC, StanevPrime commented on packages/widget_toolkit/lib/src/base/theme/widget_toolkit_theme.dart
> +    required this.textColorWhite,
Please avoid exact colors

2024-04-05 08:19 UTC, StanevPrime requested changes
Please fix the golden files and the mentioned theme properties

2024-04-05 08:19 UTC, StanevPrime commented on packages/widget_toolkit/lib/src/lib_text_field_dialog/theme/text_field_dialog_theme.dart
> +    required this.textFieldDialog2,
Please improve the naming

2024-04-05 08:19 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/dark_theme/edit_address_empty.png
Please fix the appearance

2024-04-05 08:19 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/dark_theme/edit_address_widget.png
Same as above

2024-04-05 08:19 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/dark_theme/edit_address_success.png
Same as above

2024-04-05 08:19 UTC, StanevPrime commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/dark_theme/pin_code_error.png
Please fix the golden file

2024-05-09 08:19 UTC, StanevPrime requested changes

2024-05-09 08:19 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/dark_theme/edit_address_success.png
@DDavidPrime please fix the font of the added file

2024-05-09 08:19 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_text_field_dialog/view/goldens/dark_theme/text_field_dialog_error.png
@DDavidPrime, please fix the text field background color

2024-05-09 08:19 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_text_field_dialog/view/goldens/dark_theme/text_field_dialog_loading.png
@DDavidPrime, same as above.

2024-05-09 08:19 UTC, StanevPrime commented on packages/widget_toolkit_otp/test/sms_code_field/view/goldens/light_theme/sms_code_field_golden_success_non_obscured.png
@DDavidPrime, please confirm the background color is themable

2024-05-09 08:19 UTC, StanevPrime commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/dark_theme/pin_code_loading.png
Please bring back the biometrics button

2024-05-09 08:19 UTC, StanevPrime commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/dark_theme/pin_code_success.png
Please bring back the biometrics button

2024-05-09 08:19 UTC, StanevPrime commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/light_theme/pin_code_loading.png
Please bring back the biometrics button

2024-05-09 08:19 UTC, StanevPrime commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/light_theme/pin_code_success.png
Please bring back the biometrics button

2024-05-09 08:46 UTC, DDavidPrime commented on packages/widget_toolkit_otp/test/sms_code_field/view/goldens/light_theme/sms_code_field_golden_success_non_obscured.png
As it turns out, the only component in this example that we have access to is the pin code field itself. The surrounding background is part of the golden toolkit package (similar to the dark mode background color change).

2024-05-10 13:06 UTC, StanevPrime approved these changes

2024-05-10 14:02 UTC, merged