Fix/modal sheet paddings
Prime-Holding/widget_toolkit pull request #25
Opened 2023-03-14 08:06 UTC by RomanovaPrime

Regarding request from @PVGeorgievPrime I made changes to paddings in modal pages in the project:
 - set safeAreaBottom = false by default
 - set default content padding for showBlurredBottomSheet
 - adjust paddings where we use showBlurredBottomSheet

In addition I moved additionalBottomPadding from the ModalConfiguration into WidgetToolkitTheme

2023-03-14 13:12 UTC, StanevPrime requested changes

2023-03-14 13:12 UTC, StanevPrime commented on packages/widget_toolkit/CHANGELOG.md
> +## [0.0.1-dev7] - TBE
dev6 is not released yet, so please add your changes in the release notes below

2023-03-14 13:12 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/dark_theme/edit_address_loading.png
The new screenshots does not look good

2023-03-14 13:12 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/dark_theme/edit_address_success.png
Same as above

2023-03-14 13:12 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/light_theme/edit_address_loading.png
Same as above

2023-03-14 13:12 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/light_theme/edit_address_success.png
Same as above

2023-03-14 13:12 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_item_picker/view/goldens/dark_theme/item_picker_empty.png
Same as above

2023-03-14 13:12 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_item_picker/view/goldens/dark_theme/item_picker_error.png
Same as above

2023-03-14 13:12 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_item_picker/view/goldens/dark_theme/item_picker_loading.png
Same as above

2023-03-14 13:12 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_item_picker/view/goldens/dark_theme/item_picker_success.png
Same as above

2023-03-14 22:04 UTC, RomanovaPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/dark_theme/edit_address_loading.png
Since currently the modal page provide that padding, I had to remove it from those widgets.
I considered to add some padding around tested widgets inside factories. Is that what you have in mind?

2023-03-15 09:53 UTC, StanevPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/dark_theme/edit_address_loading.png
The goal of this ticket is to set the good-looking default behavior as well a customisation points. From what I see the main objective is not met, since in each project we need to adjust the default behaviour in order to provide a good looking UI

2023-03-15 10:18 UTC, RomanovaPrime commented on packages/widget_toolkit/test/lib_edit_address/view/goldens/dark_theme/edit_address_loading.png
Before changes, the blurredModalSheet got a WidgetBuilder as its content. All places where we used it we provided default paggings to wrap the content.  But in case we used the blurredModalSheet on its own, we had to wrap the WidgetBuilder into Padding each end every time. 
Currently default customizable padding is provided from the blurredModalSheet to wrap its content (the WidgetBuilder).  That is why we had to set default paddings of widgets, witch we place as content of  blurredModalSheet, to EdgeInsets.zero. In result goldens for those widgets looks expanded to fill all available place.

2023-03-15 14:53 UTC, StanevPrime approved these changes

2023-03-15 14:56 UTC, merged