widget_toolkit_otp - Package and Example
Prime-Holding/widget_toolkit pull request #38
Opened 2023-03-22 16:30 UTC by GoranPrime

closes #19

2023-03-22 20:36 UTC, StanevPrime requested changes

2023-03-22 20:36 UTC, StanevPrime commented on packages/widget_toolkit_otp/example/lib/main.dart
@GoranPrime the purpose of the example is to showcase the package with minimal code so that everyone can see the value of it. From one hand it's great what you have built but from another is way to complex than needed for the purpose of the example. Could you please build just one page with all the components the same way as they will be  composed in a real case scenario ?

2023-03-22 20:40 UTC, StanevPrime requested changes

2023-03-22 20:40 UTC, StanevPrime commented on packages/widget_toolkit_otp/lib/widget_toolkit_otp.dart
> +export 'package:pinput/pinput.dart'
I believe in this case we can afford reimplementing those enums so that we don't need to export third-party package specific classes.

2023-03-23 09:04 UTC, GoranPrime commented on packages/widget_toolkit_otp/example/lib/main.dart
Understood. I mostly tried to get a feel for how the package would be used, and what needed to be added, adjusted or fixed through building the different examples. But you have a point that it's become too cluttered in the end 😃

2023-03-23 17:56 UTC, StanevPrime requested changes

2023-03-23 17:56 UTC, StanevPrime commented on packages/widget_toolkit_otp/CHANGELOG.md
> +* Initial release
Please change the version to 0.0.1-dev1 and add an meaningful release notes

2023-03-23 17:56 UTC, StanevPrime commented on packages/widget_toolkit_otp/README.md
> +`Prime SMS Code` package contains a number of useful widgets that can help you in building sms/pin
Please add a .gif

2023-03-23 17:56 UTC, StanevPrime commented on packages/widget_toolkit_otp/README.md
> +prime_sms_code:
prime_sms_code ... please revise the entire README file

2023-03-23 17:56 UTC, StanevPrime commented on packages/widget_toolkit_otp/lib/src/base/extensions/error_model_extensions.dart
> +      this is ErrorModel ? this as ErrorModel : ErrorUnknown(exception: this);
We need to find a better way of handling the errors across the app and the packahe

2023-03-23 17:56 UTC, StanevPrime commented on packages/widget_toolkit_otp/lib/src/lib_countdown_widget/widgets/countdown_widget.dart
> +  static Widget withDependencies({
Avoid using `withDependencies` . Sync this with @PVGeorgievPrime

2023-03-23 17:56 UTC, StanevPrime commented on packages/widget_toolkit_otp/lib/src/lib_sms_code_field/sms_code_field.dart
> +        /// toolbarOptions has been deprecated
Please remove all commended code

2023-03-23 17:56 UTC, StanevPrime commented on packages/widget_toolkit_otp/lib/src/lib_sms_code_verification/bloc/sms_code_bloc.dart
> +            .setResultStateHandler(this)
The bloc must registered as state handler just once, not every time when _verifyCodeEvent is called

2023-03-23 17:56 UTC, StanevPrime commented on packages/widget_toolkit_otp/lib/widget_toolkit_otp.dart
> +export 'src/lib_sms_code_verification/widgets/sms_code_widget.dart';
Please ensure only the needed classes are exported

2023-03-23 17:56 UTC, StanevPrime commented on packages/widget_toolkit_otp/pubspec.yaml
> +version: 0.0.1
Let's use the pre-release version a.k.a 0.0.1.dev1

2023-03-26 18:01 UTC, StanevPrime approved these changes
In general looks good. I left a couple of cosmetic comments

2023-03-26 18:01 UTC, StanevPrime commented on packages/widget_toolkit_otp/README.md
> +To use the implemented business logic, you first need to provide in the context SmsCodeBloc and
Please add some code snippets similar to this one https://pub.dev/documentation/widget_toolkit/latest/topics/Item%20Picker-topic.html

2023-03-26 18:03 UTC, StanevPrime commented on packages/widget_toolkit_otp/README.md
> +`Prime SMS Code` package contains a number of useful widgets that can help you in building sms/pin
Do not forget to add the assets in pubspec as well 

Have a look here for an example:
https://github.com/Prime-Holding/widget_toolkit/blob/d4b61a3dd2e53ece58b069f4b2e988ed3729f4f0/packages/widget_toolkit/pubspec.yaml#L71

2023-03-26 18:09 UTC, StanevPrime commented on packages/widget_toolkit_otp/README.md
> +`Prime SMS Code` package contains a number of useful widgets that can help you in building sms/pin
Also please add the new package to the sections
- Packages
- Documentation
- Samples

2023-03-28 17:38 UTC, merged