update edit address widget content after the address is saved
Prime-Holding/widget_toolkit pull request #7
Opened 2023-02-28 13:32 UTC by StanislavPrime

update The Edit_Address_Widget content after the address is saved

2023-03-01 14:35 UTC, RomanovaPrime reviewed
I am a bit confused - Why we would like to provide EditAddressBloc outside the edit psge? That will breack the Single responsibility principle. In my head we have a single repository for user's data which cares about the address. Then we have ProfileDataBloc, where we just read values and present that value to the EditAddressWidget (our widget will just receive the initial value, how it was implemented). After the user press that widget the EditAddressBloc will be instantiated and its EditAddressService will reach out UserDataRepository to read the initial address and to update its value.  
To update the value in the EditAddressWidget we can rebuild it after the modal pops (with fetching the address again) or we can return the updated address from the modal (onAddressSaved) instead of returning void.

2023-03-01 14:35 UTC, RomanovaPrime commented on lib/src/lib_edit_address/views/edit_address_page.dart
>    }) =>
I believe that we don't need additional builder, if it returns the default one.

2023-03-04 13:58 UTC, StanevPrime requested changes

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_edit_address/ui_components/address_for_correspondence_bottom_sheet.dart
>  void showAppAddressForCorrespondence<T extends PickerItemModel>(
Or `showEditAddressBottomSheet` ?

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_edit_address/ui_components/address_for_correspondence_bottom_sheet.dart
> +  var editAddressBlocType = context.read<EditAddressBlocType>();
A couple of lines below you use the `EditAddressPage.withDependencies`, which means that there is no need of injecting the `editAddressBlocType` as a separate prop

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_edit_address/ui_components/edit_address_form.dart
> +  final EditAddressBlocType blocType;
See the comment above

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_edit_address/ui_components/edit_address_form.dart
> +        bloc: blocType,
See the comment above

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_edit_address/ui_components/edit_address_form.dart
> +                bloc: blocType,
See the comment above

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_edit_address/ui_components/edit_address_form.dart
> +    required EditAddressBlocType blocType,
See the comment above

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_edit_address/ui_components/edit_address_form.dart
> +        blocType: blocType,
See the comment above

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_edit_address/ui_components/edit_address_widget.dart
> +  Widget build(BuildContext context) => MultiProvider(
Please follow the established convention (withDependencies)

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_edit_address/views/edit_address_page.dart
> +  final EditAddressBlocType editAddressBlocType;
Please use the established DI instead of injecting the bloc manually

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_ui_components/message_panel_error.dart
> +    this.bloc,
Do not use  manual injection. See the comment above

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_ui_components/message_panel_error.dart
> +  final BlocType? bloc;
Do not use manual injection. See the comment above

2023-03-04 13:58 UTC, StanevPrime commented on lib/src/lib_ui_components/message_panel_error.dart
> +        bloc: bloc,
Do not use manual injection. See the comment above

2023-03-04 13:58 UTC, StanevPrime commented on test/lib_edit_address/factory/edit_address_factory.dart
> +            editAddressBlocType: context.read<EditAddressBlocType>(),
Do not use manual injection. See the comment above

2023-03-04 14:02 UTC, StanevPrime commented on .run/Build Runner Build.run.xml
> -    <option name="INTERPRETER_PATH" value="/bin/zsh" />
@StanislavPrime, please review your own PRs so that such kind of comments are minimised.

2023-03-04 15:34 UTC, StanislavPrime commented on lib/src/lib_edit_address/ui_components/address_for_correspondence_bottom_sheet.dart
>  void showAppAddressForCorrespondence<T extends PickerItemModel>(
This was renamed

2023-03-04 15:43 UTC, StanislavPrime commented on .run/Build Runner Build.run.xml
> -    <option name="INTERPRETER_PATH" value="/bin/zsh" />
Yes, I haven't noticed this so I returned the file content to its initial content

2023-03-06 16:51 UTC, StanevPrime commented
@StanislavPrime, can we close this PR ?

2023-03-06 17:34 UTC, closed without merging