Refactoring/widget toolkit pin
Prime-Holding/widget_toolkit pull request #80
Opened 2023-08-10 17:04 UTC by zdravkoc

Close: #79

2023-08-14 05:02 UTC, PrimeSwiftArt requested changes

2023-08-14 05:02 UTC, PrimeSwiftArt commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/ui_components/pin_code_biometric_key_with_auto_submit.dart
>    const PinCodeBiometricKeyWithAutoSubmit({
The name of this widget must be `PinCodeBiometricsKey`. It is just a button without any auto submit logic inside it. This logic must be inside the bloc.

2023-08-16 13:54 UTC, PrimeSwiftArt requested changes

2023-08-16 13:54 UTC, PrimeSwiftArt commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart
> +  ConnectableStream<void> get requestBiometricsAuthentication;
After a revision I've realised that we can remove this states. It is done by BiometricsService from the bloc.

2023-08-21 10:56 UTC, StanislavPrime requested changes

2023-08-21 10:56 UTC, StanislavPrime commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart
> +    bool isDeviceSupported =
The variables in this method method could be changed to `final`

2023-08-21 14:20 UTC, zdravkoc commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart
> -  /// Returns true if the biometrics of the phone are enabled for usage from the app
We agreed that it's not necessary and we will not use it

2023-08-23 11:40 UTC, StanislavPrime reviewed
Improvements suggestions:
- In the `PinCodeService` there is one comment, which is longer than 80 on the 2nd line, above `isPinCodeInSecureStorage`.
- In the `ErrorWrongPin` doc comments there is this `[PinCodeComponent]` , which should not be in  square brackets, because it is out of scope. https://dart.dev/tools/linter-rules/comment_references.
- In `PinCodeComponent` line 49 exceed the 80 char limit :/// [mapBiometricMessageToString] will be used to translate the [BiometricsMessage] 
  - line 60 also:   /// Provide custom implementation for the most down right button. Do not forget
  - The 2 variables in _calculateRowLength method on line line 364 could be changed to final without a type.
  - line _buildButtonContent could be changed to return with `=>`
- `PinCodeDeleteKey` constructor the required element on line 8 `required this.onTap,` should be first
- `PinCodeKeyboard` 80 char limit exceeded on line 63,71,85,86,98

2023-08-23 11:40 UTC, StanislavPrime commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart
> +    final String encryptedPin = await pinCodeService.encryptPinCode(pinCode);
Here even the type of `String` and `bool` could be omitted

2023-08-23 11:40 UTC, StanislavPrime commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart
> +    final bool isDeviceSupported =
In this method also the variables could be written only with final  without the type , like: `final isDeviceSupported `

2023-08-23 11:40 UTC, StanislavPrime commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart
> +        final int storedPinLength = await pinCodeService.getPinLength();
Here also the variables `storedPinLength, isCorrectPin`  could be written only with final without the type

2023-08-23 11:40 UTC, StanislavPrime commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/models/error_enable_biometrics.dart
Here a comment could be added above the class `ErrorEnableBiometrics` with explanation when it is used. In the `ErrorWrongPin` doc comments there is this `[PinCodeComponent]` , which should not be in  square brackets, because it is out of scope. https://dart.dev/tools/linter-rules/comment_references

2023-08-24 12:25 UTC, StanislavPrime approved these changes

2023-08-24 13:14 UTC, StanevPrime submitted a review, later dismissed

2023-08-24 13:14 UTC, StanevPrime commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/dark_theme/pin_code_biometrics_enabled.png
Why the message has been removed ?

2023-08-24 13:14 UTC, StanevPrime commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/dark_theme/pin_code_loading.png
Why the loading animation has been removed ?

2023-08-24 13:14 UTC, StanevPrime commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/light_theme/pin_code_biometrics.png
Why the biometrics button has been deleted ?

2023-08-24 13:14 UTC, StanevPrime commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/light_theme/pin_code_biometrics_enabled.png
Why the success message has been removed ?

2023-08-29 09:18 UTC, zdravkoc commented on packages/widget_toolkit_pin/test/lib_pin_code/view/goldens/light_theme/pin_code_biometrics_enabled.png
We will not enable biometrics from here, just authenticate, there is no need to show message.

2023-09-07 10:52 UTC, StanislavPrime commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart
> +      _pinCode.add(_pinCode.value += digit);
Here instead of `+=` only `+` could be used for the string concatenation

2023-09-07 11:34 UTC, StanislavPrime commented on packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart
>    final String enterPinWithBiometrics;
I think the name of this variable `enterPinWithBiometrics` should better be named `localizedReason` as it is in the other layers

2023-09-13 12:55 UTC, PetkovPrime approved these changes

2023-09-13 13:05 UTC, PrimeSwiftArt approved these changes

2023-09-14 09:48 UTC, merged